#!/usr/bin/env python3
"""Generate mockups/tokens.css from the two theme values.ini files.

values.ini is a flat `@key=#hex` file (no INI sections). Dark theme lives in
themes/default/, light in themes/light/ — same key set, test-enforced.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
THEMES = {"dark": "default", "light": "light"}
OUT = ROOT / "docs/design/ux-modernization/mockups/tokens.css"


def read_tokens(theme_dir: str) -> dict:
    ini = ROOT / f"shared/nexis/static/themes/{theme_dir}/style/values.ini"
    tokens = {}
    for line in ini.read_text().splitlines():
        line = line.strip()
        if not line.startswith("@") or "=" not in line:
            continue
        key, value = line[1:].split("=", 1)
        tokens[key] = value
    return tokens


blocks = ["/* GENERATED by scripts/design/tokens_to_css.py — do not edit. */\n"]
for scheme, theme_dir in THEMES.items():
    tokens = read_tokens(theme_dir)
    body = "\n".join(f"  --{k}: {v};" for k, v in sorted(tokens.items()))
    selector = ":root" if scheme == "dark" else ':root[data-theme="light"]'
    blocks.append(f"{selector} {{\n{body}\n}}\n")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(blocks))
print(f"Wrote {OUT}")
