// FW-14 (SSO-3742): HealthReportManager — on-demand Markdown export + schedule CRUD.
//
// Uses the live singleton against real system data (same approach as
// CleanerServiceTests and DataRefreshServiceTests) and a QTemporaryDir so no
// Documents-location files leak outside the test run.

#include <QTest>
#include <QTemporaryDir>
#include <QFile>
#include <QFileInfo>
#include <QStandardPaths>
#include "Managers/health_report_manager.h"

class TestHealthReport : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase();
    void cleanupTestCase();

    // ── On-demand report generation ──────────────────────────────────────────
    void generateReport_createsFile();
    void generateReport_containsExpectedSections();
    void generateReport_markdownWellFormed();
    void generateReport_toDirectory_createsTimestampedFile();
    void generateReport_toExplicitPath_writesToThatPath();

    // ── Schedule CRUD ─────────────────────────────────────────────────────────
    void createSchedule_returnsNonEmptyId();
    void createSchedule_persists();
    void updateSchedule_changesField();
    void deleteSchedule_removesEntry();
    void getSchedule_unknownId_returnsEmpty();

private:
    QTemporaryDir m_tmpDir;
};

void TestHealthReport::initTestCase()
{
    QVERIFY(m_tmpDir.isValid());
    // Redirect QStandardPaths so generateReport() doesn't write to ~/Documents.
    QStandardPaths::setTestModeEnabled(true);
}

void TestHealthReport::cleanupTestCase()
{
    QStandardPaths::setTestModeEnabled(false);
}

// ── On-demand report generation ───────────────────────────────────────────────

void TestHealthReport::generateReport_createsFile()
{
    QString outPath = m_tmpDir.filePath("report1.md");
    QString result = HealthReportManager::ins()->generateReport(outPath);
    QVERIFY(!result.isEmpty());
    QVERIFY(QFile::exists(result));
    QVERIFY(QFileInfo(result).size() > 0);
}

void TestHealthReport::generateReport_containsExpectedSections()
{
    QString outPath = m_tmpDir.filePath("report2.md");
    QString result = HealthReportManager::ins()->generateReport(outPath);
    QVERIFY(!result.isEmpty());

    QFile f(result);
    QVERIFY(f.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(f.readAll());

    QVERIFY2(content.contains("# Nexis Health Report"), "Missing report title");
    QVERIFY2(content.contains("## CPU"), "Missing CPU section");
    QVERIFY2(content.contains("## Memory"), "Missing Memory section");
    QVERIFY2(content.contains("## Disk Usage"), "Missing Disk Usage section");
    QVERIFY2(content.contains("## Drive Health (SMART)"), "Missing Drive Health section");
    QVERIFY2(content.contains("## Thermal Sensors"), "Missing Thermal Sensors section");
    QVERIFY2(content.contains("## GPU"), "Missing GPU section");
    QVERIFY2(content.contains("## Battery"), "Missing Battery section");
    QVERIFY2(content.contains("## Cleanable Space"), "Missing Cleanable Space section");
}

void TestHealthReport::generateReport_markdownWellFormed()
{
    QString outPath = m_tmpDir.filePath("report3.md");
    QString result = HealthReportManager::ins()->generateReport(outPath);
    QVERIFY(!result.isEmpty());

    QFile f(result);
    QVERIFY(f.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(f.readAll());

    // Document starts with level-1 heading.
    QVERIFY2(content.startsWith("# "), "Report must begin with a level-1 heading");

    // Contains the separator and footer.
    QVERIFY2(content.contains("---"), "Report must contain at least one horizontal rule");
    QVERIFY2(content.contains("_Report generated by"), "Footer text missing");

    // All section headings use ##.
    // No orphaned heading levels (### appears only under SMART sub-drives).
    QStringList lines = content.split('\n');
    bool hasH2 = false;
    for (const QString &line : lines) {
        if (line.startsWith("## ")) { hasH2 = true; break; }
    }
    QVERIFY2(hasH2, "Report must have at least one ## section heading");
}

void TestHealthReport::generateReport_toDirectory_createsTimestampedFile()
{
    // Passing a directory path should produce a nexis-health-<ts>.md file.
    QString dir = m_tmpDir.path();
    QString result = HealthReportManager::ins()->generateReport(dir);
    QVERIFY(!result.isEmpty());
    QVERIFY(QFile::exists(result));
    QVERIFY(QFileInfo(result).fileName().startsWith("nexis-health-"));
    QVERIFY(QFileInfo(result).suffix() == "md");
}

void TestHealthReport::generateReport_toExplicitPath_writesToThatPath()
{
    QString outPath = m_tmpDir.filePath("custom_name.md");
    QString result = HealthReportManager::ins()->generateReport(outPath);
    QCOMPARE(result, outPath);
    QVERIFY(QFile::exists(outPath));
}

// ── Schedule CRUD ─────────────────────────────────────────────────────────────

void TestHealthReport::createSchedule_returnsNonEmptyId()
{
    HealthReportManager::ReportSchedule s;
    s.name = "TestSchedule";
    s.outputDir = m_tmpDir.path();
    QString id = HealthReportManager::ins()->createReportSchedule(s);
    QVERIFY(!id.isEmpty());
    // Clean up to avoid polluting other tests.
    HealthReportManager::ins()->deleteReportSchedule(id);
}

void TestHealthReport::createSchedule_persists()
{
    HealthReportManager::ReportSchedule s;
    s.name = "PersistTest";
    s.hour = 3;
    s.minute = 30;
    s.outputDir = m_tmpDir.path();
    QString id = HealthReportManager::ins()->createReportSchedule(s);
    QVERIFY(!id.isEmpty());

    HealthReportManager::ReportSchedule loaded =
        HealthReportManager::ins()->getReportSchedule(id);
    QCOMPARE(loaded.id, id);
    QCOMPARE(loaded.name, QString("PersistTest"));
    QCOMPARE(loaded.hour, 3);
    QCOMPARE(loaded.minute, 30);

    HealthReportManager::ins()->deleteReportSchedule(id);
}

void TestHealthReport::updateSchedule_changesField()
{
    HealthReportManager::ReportSchedule s;
    s.name = "UpdateTest";
    s.hour = 8;
    s.outputDir = m_tmpDir.path();
    QString id = HealthReportManager::ins()->createReportSchedule(s);

    HealthReportManager::ReportSchedule updated =
        HealthReportManager::ins()->getReportSchedule(id);
    updated.hour = 22;
    HealthReportManager::ins()->updateReportSchedule(updated);

    HealthReportManager::ReportSchedule reloaded =
        HealthReportManager::ins()->getReportSchedule(id);
    QCOMPARE(reloaded.hour, 22);

    HealthReportManager::ins()->deleteReportSchedule(id);
}

void TestHealthReport::deleteSchedule_removesEntry()
{
    HealthReportManager::ReportSchedule s;
    s.name = "DeleteTest";
    s.outputDir = m_tmpDir.path();
    QString id = HealthReportManager::ins()->createReportSchedule(s);
    QVERIFY(!id.isEmpty());

    HealthReportManager::ins()->deleteReportSchedule(id);

    HealthReportManager::ReportSchedule gone =
        HealthReportManager::ins()->getReportSchedule(id);
    QVERIFY(gone.id.isEmpty());
}

void TestHealthReport::getSchedule_unknownId_returnsEmpty()
{
    HealthReportManager::ReportSchedule r =
        HealthReportManager::ins()->getReportSchedule("does-not-exist-xyz-123");
    QVERIFY(r.id.isEmpty());
}

QTEST_MAIN(TestHealthReport)
#include "test_health_report.moc"
