#!/usr/bin/env python3
"""Regenerate the derivable stats table in docs/APPLICATION_OVERVIEW.md.

These counters used to be hand-incremented by every PR, which made a single
table row the most-contended line in the repo — concurrent PRs each bumped
"Source files" by one and every merge invalidated the rest (SSO-23891,
SSO-23951). They are all mechanically derivable, so a script owns them now.

The generated rows live between the NEXIS-STATS markers in
docs/APPLICATION_OVERVIEW.md. Everything outside those markers, including the
curated component table, stays hand-written.

Usage:
  gen_doc_stats.py            # rewrite the marked block in place
  gen_doc_stats.py --check    # exit 1 if the block is stale (CI / release gate)
  gen_doc_stats.py --print    # print the computed values, touch nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OVERVIEW = REPO_ROOT / "docs" / "APPLICATION_OVERVIEW.md"

BEGIN = "<!-- BEGIN NEXIS-STATS (generated by scripts/gen_doc_stats.py — do not hand-edit) -->"
END = "<!-- END NEXIS-STATS -->"

SOURCE_DIRS = ["shared", "linux", "macos"]
SOURCE_EXTS = {".cpp", ".h", ".mm"}


def tracked_files() -> list[Path]:
    """List git-tracked files, so build/ and untracked scratch never skew counts."""
    out = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [Path(p) for p in out.split("\0") if p]


def line_count(paths: list[Path]) -> int:
    total = 0
    for p in paths:
        try:
            with (REPO_ROOT / p).open("rb") as fh:
                total += sum(1 for _ in fh)
        except OSError:
            pass
    return total


def approx(n: int) -> str:
    """Round LOC to a stable magnitude so trivial edits don't churn the doc."""
    if n >= 10_000:
        return f"~{round(n, -2):,}"
    return f"~{round(n, -1):,}"


def compute() -> list[tuple[str, str, str]]:
    files = tracked_files()

    src = [
        p
        for p in files
        if p.parts and p.parts[0] in SOURCE_DIRS and p.suffix in SOURCE_EXTS
    ]
    tests = [
        p for p in files if p.parts and p.parts[0] == "tests" and p.suffix in {".cpp", ".h"}
    ]
    translations = [
        p for p in files if p.match("shared/translations/*.ts")
    ]

    cmake = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    m = re.search(r"project\s*\([^)]*VERSION\s+(\d+\.\d+\.\d+)", cmake)
    version = m.group(1) if m else "unknown"

    tests_cmake = (REPO_ROOT / "tests" / "CMakeLists.txt").read_text(encoding="utf-8")
    unit = len(re.findall(r"^\s*add_nexis_test\(", tests_cmake, re.MULTILINE))
    extra = len(re.findall(r"^\s*add_executable\(", tests_cmake, re.MULTILINE))

    # Test methods = slots declared after a `private slots:` label in a test TU.
    methods = 0
    for p in tests:
        if not p.name.startswith("test_"):
            continue
        text = (REPO_ROOT / p).read_text(encoding="utf-8", errors="replace")
        for block in re.split(r"private\s+slots\s*:", text)[1:]:
            block = re.split(r"^\s*(?:public|private|protected|signals)\b", block, maxsplit=1, flags=re.MULTILINE)[0]
            methods += len(re.findall(r"^\s*void\s+\w+\s*\(\s*\)\s*;", block, re.MULTILINE))

    return [
        ("Version", version, "`project(... VERSION ...)` in `CMakeLists.txt`"),
        ("Source LOC (C++)", approx(line_count(src)), "`shared/`, `linux/`, `macos/` (`*.cpp`/`*.h`/`*.mm`)"),
        ("Source files (C++)", f"{len(src):,}", "same"),
        ("Test LOC", approx(line_count(tests)), "`tests/`"),
        (
            "Test executables",
            f"{unit + extra} ({unit} unit + {extra} screenshot; some platform-gated)",
            "`add_nexis_test()` / `add_executable()` in `tests/CMakeLists.txt`",
        ),
        ("Test methods", f"~{methods}", "`private slots:` in `tests/*/test_*.cpp`"),
        ("Translations", f"{len(translations)} languages", "`shared/translations/*.ts`"),
    ]


def render_block() -> str:
    rows = compute()
    lines = [
        BEGIN,
        "",
        "| Metric | Value | Source of truth |",
        "|--------|-------|-----------------|",
    ]
    lines += [f"| {name} | {value} | {src} |" for name, value, src in rows]
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"error: {OVERVIEW.relative_to(REPO_ROOT)} is missing the NEXIS-STATS markers"
        )
    return text[:start] + block + text[end + len(END) :]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    ap.add_argument("--print", dest="show", action="store_true", help="print values only")
    args = ap.parse_args()

    if args.show:
        for name, value, _ in compute():
            print(f"{name:22} {value}")
        return 0

    text = OVERVIEW.read_text(encoding="utf-8")
    new = splice(text, render_block())

    if args.check:
        if new != text:
            print(
                "error: docs/APPLICATION_OVERVIEW.md stats block is stale.\n"
                "       Run: python3 scripts/gen_doc_stats.py",
                file=sys.stderr,
            )
            return 1
        print("docs/APPLICATION_OVERVIEW.md stats block is up to date")
        return 0

    if new == text:
        print("docs/APPLICATION_OVERVIEW.md stats block already up to date")
    else:
        OVERVIEW.write_text(new, encoding="utf-8")
        print("docs/APPLICATION_OVERVIEW.md stats block regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
