#!/usr/bin/env python3
"""Regenerate every version mention this repo can derive mechanically.

This script owns **both** places the release version appears in the living
docs, in both files:

1. The NEXIS-STATS table's `| Version |` row — `docs/APPLICATION_OVERVIEW.md`
   only.
2. The prose `> Last updated: YYYY-MM-DD (...) | Version X.Y.Z` header line —
   `docs/APPLICATION_OVERVIEW.md` **and** `docs/ARCHITECTURE_REVIEW.md`. The
   date is set to today (UTC); the parenthetical SSO/issue-id list is
   hand-curated provenance and is left untouched.

These counters used to be hand-incremented by every PR, which made a single
table row the most-contended line in the repo — concurrent PRs each bumped
"Source files" by one and every merge invalidated the rest (SSO-23891,
SSO-23951). They are all mechanically derivable, so a script owns them now.
The header line had the same problem in miniature: nothing wrote it, so
`scripts/check_doc_versions.sh` (which reads it) went stale on every release
cut until this script started owning it too (SSO-24822).

The generated rows live between the NEXIS-STATS markers in
docs/APPLICATION_OVERVIEW.md. Everything outside those markers and the header
line, including the curated component table, stays hand-written.

Usage:
  gen_doc_stats.py            # rewrite the stats block and version headers in place
  gen_doc_stats.py --check    # exit 1 if the stats block or header VERSION is stale
                               # (the header DATE is ignored — see blank_header_date())
  gen_doc_stats.py --print    # print the computed values, touch nothing
"""

from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OVERVIEW = REPO_ROOT / "docs" / "APPLICATION_OVERVIEW.md"
ARCHITECTURE_REVIEW = REPO_ROOT / "docs" / "ARCHITECTURE_REVIEW.md"

BEGIN = "<!-- BEGIN NEXIS-STATS (generated by scripts/gen_doc_stats.py — do not hand-edit) -->"
END = "<!-- END NEXIS-STATS -->"

# Matches "> Last updated: YYYY-MM-DD (hand-curated SSO/issue list) | Version X.Y.Z".
# The parenthetical never contains ")" itself, so [^)]* is a safe, simple bound.
# Date and version are captured separately (groups 2 and 4) so --check can
# blank out just the date before comparing — see blank_header_date().
HEADER_RE = re.compile(
    r"(> Last updated: )(\d{4}-\d{2}-\d{2})(\s*\([^)]*\)\s*\|\s*Version\s+)(\d+\.\d+\.\d+)"
)

SOURCE_DIRS = ["shared", "linux", "macos"]
SOURCE_EXTS = {".cpp", ".h", ".mm"}


def tracked_files() -> list[Path]:
    """List git-tracked files, so build/ and untracked scratch never skew counts."""
    out = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [Path(p) for p in out.split("\0") if p]


def line_count(paths: list[Path]) -> int:
    total = 0
    for p in paths:
        try:
            with (REPO_ROOT / p).open("rb") as fh:
                total += sum(1 for _ in fh)
        except OSError:
            pass
    return total


def approx(n: int) -> str:
    """Round LOC to a stable magnitude so trivial edits don't churn the doc."""
    if n >= 10_000:
        return f"~{round(n, -2):,}"
    return f"~{round(n, -1):,}"


def read_project_version() -> str:
    cmake = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    m = re.search(r"project\s*\([^)]*VERSION\s+(\d+\.\d+\.\d+)", cmake)
    return m.group(1) if m else "unknown"


def today_utc() -> str:
    return datetime.datetime.now(datetime.timezone.utc).date().isoformat()


def sync_header(text: str, version: str, today: str) -> str:
    """Rewrite the "Last updated ... | Version" header line in place, keeping
    the hand-curated parenthetical SSO/issue-id list untouched."""
    new_text, n = HEADER_RE.subn(rf"\g<1>{today}\g<3>{version}", text, count=1)
    if n == 0:
        raise SystemExit("error: could not find 'Last updated ... | Version' header to sync")
    return new_text


def blank_header_date(text: str) -> str:
    """Replace the header's date with a fixed placeholder.

    --check must fail on a stale version or a stale stats block, but never
    merely because the calendar day rolled over between the release cut and
    the tag push landing (SSO-24822): both write today's date, so a same-day
    rewrite is a no-op diff, but a next-day --check on an otherwise-correct
    file would spuriously report staleness without this normalization.
    """
    return HEADER_RE.sub(r"\g<1>DATE-IGNORED\g<3>\g<4>", text, count=1)


def compute() -> list[tuple[str, str, str]]:
    files = tracked_files()

    src = [
        p
        for p in files
        if p.parts and p.parts[0] in SOURCE_DIRS and p.suffix in SOURCE_EXTS
    ]
    tests = [
        p for p in files if p.parts and p.parts[0] == "tests" and p.suffix in {".cpp", ".h"}
    ]
    translations = [
        p for p in files if p.match("shared/translations/*.ts")
    ]

    version = read_project_version()

    tests_cmake = (REPO_ROOT / "tests" / "CMakeLists.txt").read_text(encoding="utf-8")
    unit = len(re.findall(r"^\s*add_nexis_test\(", tests_cmake, re.MULTILINE))
    extra = len(re.findall(r"^\s*add_executable\(", tests_cmake, re.MULTILINE))

    # Test methods = slots declared after a `private slots:` label in a test TU.
    methods = 0
    for p in tests:
        if not p.name.startswith("test_"):
            continue
        text = (REPO_ROOT / p).read_text(encoding="utf-8", errors="replace")
        for block in re.split(r"private\s+slots\s*:", text)[1:]:
            block = re.split(r"^\s*(?:public|private|protected|signals)\b", block, maxsplit=1, flags=re.MULTILINE)[0]
            methods += len(re.findall(r"^\s*void\s+\w+\s*\(\s*\)\s*;", block, re.MULTILINE))

    return [
        ("Version", version, "`project(... VERSION ...)` in `CMakeLists.txt`"),
        ("Source LOC (C++)", approx(line_count(src)), "`shared/`, `linux/`, `macos/` (`*.cpp`/`*.h`/`*.mm`)"),
        ("Source files (C++)", f"{len(src):,}", "same"),
        ("Test LOC", approx(line_count(tests)), "`tests/`"),
        (
            "Test executables",
            f"{unit + extra} ({unit} unit + {extra} screenshot; some platform-gated)",
            "`add_nexis_test()` / `add_executable()` in `tests/CMakeLists.txt`",
        ),
        ("Test methods", f"~{methods}", "`private slots:` in `tests/*/test_*.cpp`"),
        ("Translations", f"{len(translations)} languages", "`shared/translations/*.ts`"),
    ]


def render_block() -> str:
    rows = compute()
    lines = [
        BEGIN,
        "",
        "| Metric | Value | Source of truth |",
        "|--------|-------|-----------------|",
    ]
    lines += [f"| {name} | {value} | {src} |" for name, value, src in rows]
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"error: {OVERVIEW.relative_to(REPO_ROOT)} is missing the NEXIS-STATS markers"
        )
    return text[:start] + block + text[end + len(END) :]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the stats block or version headers are stale")
    ap.add_argument("--print", dest="show", action="store_true", help="print values only")
    args = ap.parse_args()

    if args.show:
        for name, value, _ in compute():
            print(f"{name:22} {value}")
        return 0

    version = read_project_version()
    today = today_utc()

    overview_text = OVERVIEW.read_text(encoding="utf-8")
    overview_new = sync_header(splice(overview_text, render_block()), version, today)

    architecture_text = ARCHITECTURE_REVIEW.read_text(encoding="utf-8")
    architecture_new = sync_header(architecture_text, version, today)

    targets = [
        (OVERVIEW, overview_text, overview_new),
        (ARCHITECTURE_REVIEW, architecture_text, architecture_new),
    ]

    if args.check:
        stale = [
            path
            for path, old, new in targets
            if blank_header_date(old) != blank_header_date(new)
        ]
        if stale:
            names = ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale)
            print(
                f"error: {names} out of date (stats block and/or version header).\n"
                "       Run: python3 scripts/gen_doc_stats.py",
                file=sys.stderr,
            )
            return 1
        print("docs stats block and version headers are up to date")
        return 0

    changed = []
    for path, old, new in targets:
        if new != old:
            path.write_text(new, encoding="utf-8")
            changed.append(path)

    if changed:
        names = ", ".join(str(path.relative_to(REPO_ROOT)) for path in changed)
        print(f"regenerated: {names}")
    else:
        print("docs stats block and version headers already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
