name: Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Ubuntu Qt6 Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            cmake \
            g++ \
            libgl1-mesa-dev \
            qt6-base-dev \
            qt6-charts-dev \
            qt6-svg-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            qt6-l10n-tools \
            libqt6charts6-dev \
            libqt6svg6-dev

      - name: Configure
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6 \
                ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: stacer-linux-x64
          path: build/output/stacer
          retention-days: 14
